#ifndef SMACK_LOG_HH
#define SMACK_LOG_HH

#include "soil/Log.hh"

#define SMACK_LOG_INIT(x) SOIL_LOG_INIT(x)

#define SMACK_TRACE SOIL_TRACE
#define SMACK_DEBUG SOIL_DEBUG
#define SMACK_INFO  SOIL_INFO
#define SMACK_WARNING SOIL_WARNING
#define SMACK_ERROR SOIL_ERROR
#define SMACK_FATAL SOIL_FATAL
#define SMACK_PDU SOIL_PDU


#endif
